/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register */
        post: operations["register_api_v1_auth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/nodes/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Nodes */
        get: operations["list_nodes_api_v1_nodes__get"];
        put?: never;
        /** Create Node */
        post: operations["create_node_api_v1_nodes__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/nodes/restore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Restore Nodes
         * @description Восстановить удалённое поддерево из снимка (Undo удаления).
         *
         *     Снимок берётся клиентом через GET /{node_id}/deletion-snapshot (удаление узла) или
         *     GET /edges/{edge_id}/deletion-snapshot (удаление/создание связи) ДО удаления.
         *     Снимок может быть узловым (поддерево) ИЛИ чисто рёберным (nodes=[]) — обе формы
         *     восстанавливаются одним путём с сохранением исходных id.
         */
        post: operations["restore_nodes_api_v1_nodes_restore_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/nodes/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search Nodes */
        get: operations["search_nodes_api_v1_nodes_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/nodes/all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List All Nodes
         * @description Плоский список ВСЕХ узлов схемы — для выбора дальнего конца связи к узлу
         *     вне текущего уровня (фронт собирает из него дерево по parent_id).
         */
        get: operations["list_all_nodes_api_v1_nodes_all_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/nodes/graph": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Root Graph
         * @description Граф корневого уровня: узлы без родителя + сквозные рёбра.
         */
        get: operations["get_root_graph_api_v1_nodes_graph_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/nodes/alerts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Alerts
         * @description Глобальные алерты незавершённости схемы (только архитектор):
         *     1) атомарные (листовые) узлы без единой связи — «подвисшие»;
         *     2) связи, у которых хотя бы один конец упирается в промежуточный
         *        (контейнерный) узел, а не в атомарный.
         *     Контейнеры в проверке (1) не участвуют: прямых связей у них быть не должно
         *     (это как раз ловит проверка 2), а группировку детей за «подвисание» не считаем.
         */
        get: operations["get_alerts_api_v1_nodes_alerts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/nodes/{node_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Node */
        get: operations["get_node_api_v1_nodes__node_id__get"];
        put?: never;
        post?: never;
        /** Delete Node */
        delete: operations["delete_node_api_v1_nodes__node_id__delete"];
        options?: never;
        head?: never;
        /** Update Node */
        patch: operations["update_node_api_v1_nodes__node_id__patch"];
        trace?: never;
    };
    "/api/v1/nodes/{node_id}/deletion-snapshot": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Deletion Snapshot
         * @description Снимок всего, что снесёт удаление узла (поддерево + рёбра + ghost-метаданные).
         *
         *     Клиент берёт его ПЕРЕД delete, чтобы потом восстановить через POST /restore (Undo).
         */
        get: operations["get_deletion_snapshot_api_v1_nodes__node_id__deletion_snapshot_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/nodes/{node_id}/children": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Children */
        get: operations["get_children_api_v1_nodes__node_id__children_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/nodes/{node_id}/descendants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Descendants
         * @description Все потомки узла на любой глубине (без самого узла) — для скоупленного
         *     выбора дальнего конца межуровневой связи: тянешь стрелку на узел-контейнер,
         *     поиск идёт только по его поддереву.
         */
        get: operations["get_descendants_api_v1_nodes__node_id__descendants_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/nodes/{node_id}/edges": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Node Edges
         * @description Внешние связи поддерева узла (он сам + потомки любой глубины) — те, что
         *     исчезнут при удалении узла: ровно один конец внутри поддерева, другой снаружи.
         *     Для предупреждения перед удалением. Чисто внутренние связи ветки не включаем —
         *     они уходят вместе с самой веткой и «потерей связи наружу» не являются.
         *     Направление/имя соседа считаются относительно поддерева (внешний конец).
         */
        get: operations["get_node_edges_api_v1_nodes__node_id__edges_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/nodes/{node_id}/graph": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Node Graph
         * @description Граф для уровня node_id: дочерние узлы + рёбра + гостевые узлы из других уровней.
         */
        get: operations["get_node_graph_api_v1_nodes__node_id__graph_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/nodes/{node_id}/context": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Node Context
         * @description Контекстная схема узла: сам узел + его прямые соседи.
         *     Сосед — другой конец связи, у которой ровно один конец лежит в поддереве
         *     фокуса (сам узел ИЛИ любой его потомок на любой глубине). Конец внутри
         *     поддерева проецируется на фокус, внешний конец — это узел-сосед.
         */
        get: operations["get_node_context_api_v1_nodes__node_id__context_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/nodes/{container_id}/ghost-positions/{node_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Save Ghost Position
         * @description Сохраняет (upsert) координаты гостевого узла node_id на уровне container_id.
         */
        put: operations["save_ghost_position_api_v1_nodes__container_id__ghost_positions__node_id__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/nodes/{container_id}/ghost-edge-handles/{edge_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Save Ghost Edge Handle
         * @description Сохраняет (upsert) хэндл гостевого конца ребра edge_id на уровне container_id,
         *     привязанный к id отображаемой сущности node_id (лист-гость ИЛИ предок-контейнер).
         *
         *     У каждой проекции гостевого конца своя строка — поэтому привязка к свёрнутому
         *     контейнеру и к развёрнутому листу хранятся раздельно и не затирают друг друга.
         */
        put: operations["save_ghost_edge_handle_api_v1_nodes__container_id__ghost_edge_handles__edge_id__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/nodes/{container_id}/edge-waypoints/{edge_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Save Edge Waypoints
         * @description Сохраняет (upsert) кастомный путь ГОСТЕВОЙ стрелки edge_id на уровне container_id.
         *
         *     Пустой список waypoints — сброс в авто-маршрут: строку пер-уровневого слоя удаляем
         *     (нет строки = авто). Путь локальной стрелки сюда не пишется — он в колонке ребра.
         */
        put: operations["save_edge_waypoints_api_v1_nodes__container_id__edge_waypoints__edge_id__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/edges/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Edges */
        get: operations["list_edges_api_v1_edges__get"];
        put?: never;
        /** Create Edge */
        post: operations["create_edge_api_v1_edges__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/edges/{edge_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Edge */
        get: operations["get_edge_api_v1_edges__edge_id__get"];
        put?: never;
        post?: never;
        /** Delete Edge */
        delete: operations["delete_edge_api_v1_edges__edge_id__delete"];
        options?: never;
        head?: never;
        /** Update Edge */
        patch: operations["update_edge_api_v1_edges__edge_id__patch"];
        trace?: never;
    };
    "/api/v1/edges/{edge_id}/deletion-snapshot": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Edge Deletion Snapshot
         * @description Снимок связи и её ghost-метаданных для отката удаления/создания (Undo).
         *
         *     Клиент берёт его ПЕРЕД delete (откат удаления связи) либо при undo создания связи,
         *     чтобы потом восстановить связь с исходным id через POST /nodes/restore.
         */
        get: operations["edge_deletion_snapshot_api_v1_edges__edge_id__deletion_snapshot_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Export All
         * @description Экспорт ВСЕЙ схемы.
         */
        get: operations["export_all_api_v1_export_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/export/{node_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Export Subtree
         * @description Экспорт поддерева от узла (сам узел + все потомки + связи внутри поддерева).
         */
        get: operations["export_subtree_api_v1_export__node_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/processes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Processes */
        get: operations["list_processes_api_v1_processes_get"];
        put?: never;
        /** Create Process */
        post: operations["create_process_api_v1_processes_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/processes/{process_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Process */
        get: operations["get_process_api_v1_processes__process_id__get"];
        put?: never;
        post?: never;
        /** Delete Process */
        delete: operations["delete_process_api_v1_processes__process_id__delete"];
        options?: never;
        head?: never;
        /** Update Process */
        patch: operations["update_process_api_v1_processes__process_id__patch"];
        trace?: never;
    };
    "/api/v1/processes/{process_id}/participants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add Participant */
        post: operations["add_participant_api_v1_processes__process_id__participants_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/processes/{process_id}/participants/reorder": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Reorder Participants */
        patch: operations["reorder_participants_api_v1_processes__process_id__participants_reorder_patch"];
        trace?: never;
    };
    "/api/v1/processes/{process_id}/participants/{participant_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Participant */
        delete: operations["delete_participant_api_v1_processes__process_id__participants__participant_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/processes/{process_id}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Message */
        post: operations["create_message_api_v1_processes__process_id__messages_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/processes/{process_id}/messages/{message_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Message */
        delete: operations["delete_message_api_v1_processes__process_id__messages__message_id__delete"];
        options?: never;
        head?: never;
        /** Update Message */
        patch: operations["update_message_api_v1_processes__process_id__messages__message_id__patch"];
        trace?: never;
    };
    "/api/v1/processes/{process_id}/fragments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Fragment */
        post: operations["create_fragment_api_v1_processes__process_id__fragments_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/processes/{process_id}/fragments/{fragment_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Fragment */
        delete: operations["delete_fragment_api_v1_processes__process_id__fragments__fragment_id__delete"];
        options?: never;
        head?: never;
        /** Update Fragment */
        patch: operations["update_fragment_api_v1_processes__process_id__fragments__fragment_id__patch"];
        trace?: never;
    };
    "/api/v1/processes/{process_id}/channels": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Channels */
        get: operations["list_channels_api_v1_processes__process_id__channels_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AlertsResponse */
        AlertsResponse: {
            /**
             * Disconnected Nodes
             * @default []
             */
            disconnected_nodes: components["schemas"]["DisconnectedNodeAlert"][];
            /**
             * Intermediate Edges
             * @default []
             */
            intermediate_edges: components["schemas"]["IntermediateEdgeAlert"][];
            /**
             * Isolated Groups
             * @default []
             */
            isolated_groups: components["schemas"]["IsolatedGroupAlert"][];
        };
        /** AncestorRef */
        AncestorRef: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /**
             * Is External
             * @default false
             */
            is_external: boolean;
        };
        /** Body_login_api_v1_auth_login_post */
        Body_login_api_v1_auth_login_post: {
            /** Grant Type */
            grant_type?: string | null;
            /** Username */
            username: string;
            /** Password */
            password: string;
            /**
             * Scope
             * @default
             */
            scope: string;
            /** Client Id */
            client_id?: string | null;
            /** Client Secret */
            client_secret?: string | null;
        };
        /** ChannelOut */
        ChannelOut: {
            /**
             * Edge Id
             * Format: uuid
             */
            edge_id: string;
            /**
             * Source Id
             * Format: uuid
             */
            source_id: string;
            /**
             * Target Id
             * Format: uuid
             */
            target_id: string;
            /** Technology */
            technology: string | null;
            /** Label */
            label: string | null;
            /** Synchronous */
            synchronous: boolean;
            /** Legs */
            legs: components["schemas"]["LegOut"][];
        };
        /**
         * DeletionSnapshot
         * @description Полный снимок того, что снёс БД-каскад при удалении узла: поддерево узлов,
         *     инцидентные рёбра и ghost-метаданные. Достаточно для точного восстановления.
         */
        "DeletionSnapshot-Input": {
            /** Nodes */
            nodes: components["schemas"]["NodeSnapshot"][];
            /** Edges */
            edges: components["schemas"]["EdgeSnapshot"][];
            /** Ghost Positions */
            ghost_positions: components["schemas"]["GhostPositionSnapshot"][];
            /** Ghost Edge Handles */
            ghost_edge_handles: components["schemas"]["GhostEdgeHandleSnapshot"][];
            /** Edge Waypoints */
            edge_waypoints: components["schemas"]["EdgeWaypointSnapshot"][];
        };
        /**
         * DeletionSnapshot
         * @description Полный снимок того, что снёс БД-каскад при удалении узла: поддерево узлов,
         *     инцидентные рёбра и ghost-метаданные. Достаточно для точного восстановления.
         */
        "DeletionSnapshot-Output": {
            /** Nodes */
            nodes: components["schemas"]["NodeSnapshot"][];
            /** Edges */
            edges: components["schemas"]["EdgeSnapshot"][];
            /** Ghost Positions */
            ghost_positions: components["schemas"]["GhostPositionSnapshot"][];
            /** Ghost Edge Handles */
            ghost_edge_handles: components["schemas"]["GhostEdgeHandleSnapshot"][];
            /** Edge Waypoints */
            edge_waypoints: components["schemas"]["EdgeWaypointSnapshot"][];
        };
        /**
         * DisconnectedNodeAlert
         * @description Атомарный узел без единой связи («подвисший»).
         */
        DisconnectedNodeAlert: {
            /**
             * Node Id
             * Format: uuid
             */
            node_id: string;
            /** Node Name */
            node_name: string;
        };
        /** EdgeCreate */
        EdgeCreate: {
            /** Label */
            label?: string | null;
            /** Technology */
            technology?: string | null;
            /**
             * Source Id
             * Format: uuid
             */
            source_id: string;
            /**
             * Target Id
             * Format: uuid
             */
            target_id: string;
            /** Source Handle */
            source_handle?: string | null;
            /** Target Handle */
            target_handle?: string | null;
        };
        /** EdgeResponse */
        EdgeResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Label */
            label: string | null;
            /** Technology */
            technology: string | null;
            /**
             * Source Id
             * Format: uuid
             */
            source_id: string;
            /**
             * Target Id
             * Format: uuid
             */
            target_id: string;
            /** Source Handle */
            source_handle: string | null;
            /** Target Handle */
            target_handle: string | null;
            /** Waypoints */
            waypoints?: components["schemas"]["Point"][] | null;
            /** Label T */
            label_t?: number | null;
            /** Is Synchronous */
            is_synchronous?: boolean | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** EdgeSnapshot */
        EdgeSnapshot: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Label */
            label?: string | null;
            /** Technology */
            technology?: string | null;
            /**
             * Source Id
             * Format: uuid
             */
            source_id: string;
            /**
             * Target Id
             * Format: uuid
             */
            target_id: string;
            /** Source Handle */
            source_handle?: string | null;
            /** Target Handle */
            target_handle?: string | null;
            /** Waypoints */
            waypoints?: components["schemas"]["Point"][] | null;
            /** Label T */
            label_t?: number | null;
        };
        /** EdgeUpdate */
        EdgeUpdate: {
            /** Label */
            label?: string | null;
            /** Technology */
            technology?: string | null;
            /** Source Id */
            source_id?: string | null;
            /** Target Id */
            target_id?: string | null;
            /** Source Handle */
            source_handle?: string | null;
            /** Target Handle */
            target_handle?: string | null;
            /** Waypoints */
            waypoints?: components["schemas"]["Point"][] | null;
            /** Label T */
            label_t?: number | null;
            /** Is Synchronous */
            is_synchronous?: boolean | null;
        };
        /** EdgeWaypointSnapshot */
        EdgeWaypointSnapshot: {
            /**
             * Container Id
             * Format: uuid
             */
            container_id: string;
            /**
             * Edge Id
             * Format: uuid
             */
            edge_id: string;
            /** Waypoints */
            waypoints: components["schemas"]["Point"][];
        };
        /** EdgeWaypointsUpdate */
        EdgeWaypointsUpdate: {
            /** Waypoints */
            waypoints: components["schemas"]["Point"][];
        };
        /**
         * ExportResponse
         * @description Экспорт схемы как текст. format держим явным полем, чтобы позже добавить
         *     другие сериализации (mermaid/json) без слома контракта; content — сам документ.
         */
        ExportResponse: {
            /**
             * Format
             * @constant
             * @enum {string}
             */
            format: "yaml";
            /** Content */
            content: string;
        };
        /** FragmentCreate */
        FragmentCreate: {
            /**
             * Kind
             * @enum {string}
             */
            kind: "alt" | "opt" | "loop" | "par";
            /** From Order */
            from_order: number;
            /** To Order */
            to_order: number;
            /** Guard */
            guard?: string | null;
            /** Else Guard */
            else_guard?: string | null;
            /** Else Order */
            else_order?: number | null;
        };
        /** FragmentOut */
        FragmentOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "alt" | "opt" | "loop" | "par";
            /** From Order */
            from_order: number;
            /** To Order */
            to_order: number;
            /** Guard */
            guard: string | null;
            /** Else Guard */
            else_guard: string | null;
            /** Else Order */
            else_order: number | null;
        };
        /** FragmentUpdate */
        FragmentUpdate: {
            /** Kind */
            kind?: ("alt" | "opt" | "loop" | "par") | null;
            /** From Order */
            from_order?: number | null;
            /** To Order */
            to_order?: number | null;
            /** Guard */
            guard?: string | null;
            /** Else Guard */
            else_guard?: string | null;
            /** Else Order */
            else_order?: number | null;
        };
        /** GhostEdgeHandleSnapshot */
        GhostEdgeHandleSnapshot: {
            /**
             * Container Id
             * Format: uuid
             */
            container_id: string;
            /**
             * Edge Id
             * Format: uuid
             */
            edge_id: string;
            /**
             * Node Id
             * Format: uuid
             */
            node_id: string;
            /** Handle */
            handle: string;
        };
        /** GhostEdgeHandleUpdate */
        GhostEdgeHandleUpdate: {
            /**
             * Node Id
             * Format: uuid
             */
            node_id: string;
            /** Handle */
            handle: string;
        };
        /** GhostNodeResponse */
        GhostNodeResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Role */
            role: string | null;
            /** Technology */
            technology: string | null;
            /** Is External */
            is_external: boolean;
            /**
             * Shape
             * @enum {string}
             */
            shape: "service" | "database" | "broker" | "person";
            /** Node Depth */
            node_depth: number;
            /**
             * Has Children
             * @default false
             */
            has_children: boolean;
            /**
             * Ancestors
             * @default []
             */
            ancestors: components["schemas"]["AncestorRef"][];
            /** Pos X */
            pos_x?: number | null;
            /** Pos Y */
            pos_y?: number | null;
            /**
             * Is Ghost
             * @default true
             * @constant
             * @enum {boolean}
             */
            is_ghost: true;
        };
        /** GhostPositionSnapshot */
        GhostPositionSnapshot: {
            /**
             * Container Id
             * Format: uuid
             */
            container_id: string;
            /**
             * Node Id
             * Format: uuid
             */
            node_id: string;
            /** Pos X */
            pos_x: number;
            /** Pos Y */
            pos_y: number;
        };
        /** GhostPositionUpdate */
        GhostPositionUpdate: {
            /** Pos X */
            pos_x: number;
            /** Pos Y */
            pos_y: number;
        };
        /** GraphEdgeResponse */
        GraphEdgeResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Label */
            label: string | null;
            /** Technology */
            technology: string | null;
            /**
             * Source Id
             * Format: uuid
             */
            source_id: string;
            /**
             * Target Id
             * Format: uuid
             */
            target_id: string;
            /**
             * Original Source Id
             * Format: uuid
             */
            original_source_id: string;
            /**
             * Original Target Id
             * Format: uuid
             */
            original_target_id: string;
            /** Original Source Name */
            original_source_name: string;
            /** Original Target Name */
            original_target_name: string;
            /** Source Handle */
            source_handle: string | null;
            /** Target Handle */
            target_handle: string | null;
            /** Waypoints */
            waypoints?: components["schemas"]["Point"][] | null;
            /** Label T */
            label_t?: number | null;
        };
        /** GraphResponse */
        GraphResponse: {
            /** Nodes */
            nodes: components["schemas"]["NodeResponse"][];
            /** Edges */
            edges: components["schemas"]["GraphEdgeResponse"][];
            /** Ghost Nodes */
            ghost_nodes: components["schemas"]["GhostNodeResponse"][];
            /**
             * Level Positions
             * @default {}
             */
            level_positions: {
                [key: string]: components["schemas"]["PosXY"];
            };
            /**
             * Level Edge Handles
             * @default {}
             */
            level_edge_handles: {
                [key: string]: string[];
            };
            /**
             * Level Edge Waypoints
             * @default {}
             */
            level_edge_waypoints: {
                [key: string]: components["schemas"]["Point"][];
            };
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * IntermediateEdgeAlert
         * @description Связь, у которой хотя бы один конец упирается в промежуточный
         *     (контейнерный) узел, а не в атомарный.
         */
        IntermediateEdgeAlert: {
            /**
             * Edge Id
             * Format: uuid
             */
            edge_id: string;
            /** Label */
            label: string | null;
            /**
             * Source Id
             * Format: uuid
             */
            source_id: string;
            /** Source Name */
            source_name: string;
            /**
             * Target Id
             * Format: uuid
             */
            target_id: string;
            /** Target Name */
            target_name: string;
            /** Source Is Intermediate */
            source_is_intermediate: boolean;
            /** Target Is Intermediate */
            target_is_intermediate: boolean;
        };
        /**
         * IsolatedGroupAlert
         * @description Изолированная группа: связная компонента графа рёбер (≥2 узла),
         *     не имеющая ни одной связи с другими частями схемы. Считается только
         *     по рёбрам (иерархия parent_id игнорируется).
         */
        IsolatedGroupAlert: {
            /** Node Ids */
            node_ids: string[];
            /** Node Names */
            node_names: string[];
        };
        /** LegOut */
        LegOut: {
            /**
             * Leg
             * @enum {string}
             */
            leg: "forward" | "return";
            /**
             * Kind
             * @enum {string}
             */
            kind: "forward" | "return" | "async";
            /**
             * From Id
             * Format: uuid
             */
            from_id: string;
            /**
             * To Id
             * Format: uuid
             */
            to_id: string;
            /** Default Caption */
            default_caption: string | null;
        };
        /** MessageCreate */
        MessageCreate: {
            /**
             * Edge Id
             * Format: uuid
             */
            edge_id: string;
            /**
             * Leg
             * @enum {string}
             */
            leg: "forward" | "return";
            /**
             * From Participant Id
             * Format: uuid
             */
            from_participant_id: string;
            /**
             * To Participant Id
             * Format: uuid
             */
            to_participant_id: string;
            /** Caption */
            caption?: string | null;
            /** Order */
            order: number;
        };
        /** MessageOut */
        MessageOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Order */
            order: number;
            /** Edge Id */
            edge_id: string | null;
            /**
             * Leg
             * @enum {string}
             */
            leg: "forward" | "return";
            /**
             * Kind
             * @enum {string}
             */
            kind: "forward" | "return" | "async";
            /** Caption */
            caption: string | null;
            /** Technology */
            technology: string | null;
            /**
             * From Id
             * Format: uuid
             */
            from_id: string;
            /**
             * To Id
             * Format: uuid
             */
            to_id: string;
            /** Valid */
            valid: boolean;
        };
        /** MessageUpdate */
        MessageUpdate: {
            /** Caption */
            caption?: string | null;
            /** Order */
            order?: number | null;
        };
        /**
         * NodeContextResponse
         * @description «Контекстная схема» узла: сам узел + его прямые соседи.
         *     Сосед — другой конец любой связи, у которой ровно один конец лежит в поддереве
         *     фокуса (сам узел или любой его потомок). Рёбра спроецированы: конец внутри
         *     поддерева свёрнут на фокус, внешний конец указывает на узел-соседа.
         *     Соседи отдаются как «гости» (пунктир), focus_ancestors — для рамок предков.
         */
        NodeContextResponse: {
            focus: components["schemas"]["NodeResponse"];
            /**
             * Focus Ancestors
             * @default []
             */
            focus_ancestors: components["schemas"]["AncestorRef"][];
            /**
             * Neighbors
             * @default []
             */
            neighbors: components["schemas"]["GhostNodeResponse"][];
            /**
             * Edges
             * @default []
             */
            edges: components["schemas"]["GraphEdgeResponse"][];
        };
        /** NodeCreate */
        NodeCreate: {
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
            /** Role */
            role?: string | null;
            /** Technology */
            technology?: string | null;
            /** Parent Id */
            parent_id?: string | null;
            /** Flowchart */
            flowchart?: string | null;
            /** Openapi Spec */
            openapi_spec?: string | null;
            /**
             * Is External
             * @default false
             */
            is_external: boolean;
            /**
             * Shape
             * @default service
             * @enum {string}
             */
            shape: "service" | "database" | "broker" | "person";
            /** Pos X */
            pos_x?: number | null;
            /** Pos Y */
            pos_y?: number | null;
        };
        /**
         * NodeEdgeInfo
         * @description Связь узла для предупреждения при удалении: направление + имя связанного узла.
         */
        NodeEdgeInfo: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Label */
            label: string | null;
            /** Technology */
            technology: string | null;
            /**
             * Direction
             * @enum {string}
             */
            direction: "outgoing" | "incoming";
            /**
             * Other Node Id
             * Format: uuid
             */
            other_node_id: string;
            /** Other Node Name */
            other_node_name: string;
        };
        /** NodeResponse */
        NodeResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Description */
            description: string | null;
            /** Role */
            role: string | null;
            /** Technology */
            technology: string | null;
            /** Parent Id */
            parent_id: string | null;
            /** Flowchart */
            flowchart: string | null;
            /** Openapi Spec */
            openapi_spec: string | null;
            /** Pos X */
            pos_x: number | null;
            /** Pos Y */
            pos_y: number | null;
            /** Is External */
            is_external: boolean;
            /**
             * Shape
             * @enum {string}
             */
            shape: "service" | "database" | "broker" | "person";
            /**
             * Child Count
             * @default 0
             */
            child_count: number;
            /**
             * Has Children
             * @default false
             */
            has_children: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** NodeSnapshot */
        NodeSnapshot: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
            /** Role */
            role?: string | null;
            /** Technology */
            technology?: string | null;
            /** Parent Id */
            parent_id?: string | null;
            /** Flowchart */
            flowchart?: string | null;
            /** Openapi Spec */
            openapi_spec?: string | null;
            /** Pos X */
            pos_x?: number | null;
            /** Pos Y */
            pos_y?: number | null;
            /**
             * Is External
             * @default false
             */
            is_external: boolean;
            /**
             * Shape
             * @default service
             * @enum {string}
             */
            shape: "service" | "database" | "broker" | "person";
        };
        /** NodeUpdate */
        NodeUpdate: {
            /** Name */
            name?: string | null;
            /** Description */
            description?: string | null;
            /** Role */
            role?: string | null;
            /** Technology */
            technology?: string | null;
            /** Parent Id */
            parent_id?: string | null;
            /** Flowchart */
            flowchart?: string | null;
            /** Openapi Spec */
            openapi_spec?: string | null;
            /** Pos X */
            pos_x?: number | null;
            /** Pos Y */
            pos_y?: number | null;
            /** Is External */
            is_external?: boolean | null;
            /** Shape */
            shape?: ("service" | "database" | "broker" | "person") | null;
        };
        /** ParticipantCreate */
        ParticipantCreate: {
            /**
             * Node Id
             * Format: uuid
             */
            node_id: string;
            /** Order */
            order: number;
        };
        /** ParticipantOut */
        ParticipantOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Node Id
             * Format: uuid
             */
            node_id: string;
            /** Name */
            name: string;
            /** Role */
            role: string | null;
            /**
             * Shape
             * @enum {string}
             */
            shape: "service" | "database" | "broker" | "person";
            /** Is External */
            is_external: boolean;
            /** Order */
            order: number;
        };
        /**
         * Point
         * @description Точка-сгиб пути стрелки в координатах графа уровня.
         */
        Point: {
            /** X */
            x: number;
            /** Y */
            y: number;
        };
        /** PosXY */
        PosXY: {
            /** Pos X */
            pos_x: number;
            /** Pos Y */
            pos_y: number;
        };
        /** ProcessCreate */
        ProcessCreate: {
            /** Name */
            name: string;
            /** Scope Node Id */
            scope_node_id?: string | null;
        };
        /** ProcessDetail */
        ProcessDetail: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Scope Node Id */
            scope_node_id: string | null;
            /** Scope Name */
            scope_name: string | null;
            /** Participants */
            participants: components["schemas"]["ParticipantOut"][];
            /** Messages */
            messages: components["schemas"]["MessageOut"][];
            /** Fragments */
            fragments: components["schemas"]["FragmentOut"][];
        };
        /** ProcessListItem */
        ProcessListItem: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Scope Node Id */
            scope_node_id: string | null;
            /** Scope Name */
            scope_name: string | null;
            /** Message Count */
            message_count: number;
        };
        /** ProcessUpdate */
        ProcessUpdate: {
            /** Name */
            name?: string | null;
            /** Scope Node Id */
            scope_node_id?: string | null;
        };
        /** ReorderPayload */
        ReorderPayload: {
            /** Ids */
            ids: string[];
        };
        /** Token */
        Token: {
            /** Access Token */
            access_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
        };
        /** UserCreate */
        UserCreate: {
            /** Username */
            username: string;
            /** Password */
            password: string;
            /**
             * Role
             * @default viewer
             */
            role: string;
        };
        /** UserResponse */
        UserResponse: {
            /** Username */
            username: string;
            /** Role */
            role: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    register_api_v1_auth_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/x-www-form-urlencoded": components["schemas"]["Body_login_api_v1_auth_login_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Token"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_nodes_api_v1_nodes__get: {
        parameters: {
            query?: {
                parent_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NodeResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_node_api_v1_nodes__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NodeCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NodeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    restore_nodes_api_v1_nodes_restore_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeletionSnapshot-Input"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_nodes_api_v1_nodes_search_get: {
        parameters: {
            query?: {
                q?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NodeResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_all_nodes_api_v1_nodes_all_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NodeResponse"][];
                };
            };
        };
    };
    get_root_graph_api_v1_nodes_graph_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GraphResponse"];
                };
            };
        };
    };
    get_alerts_api_v1_nodes_alerts_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertsResponse"];
                };
            };
        };
    };
    get_node_api_v1_nodes__node_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                node_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NodeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_node_api_v1_nodes__node_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                node_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_node_api_v1_nodes__node_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                node_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NodeUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NodeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_deletion_snapshot_api_v1_nodes__node_id__deletion_snapshot_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                node_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeletionSnapshot-Output"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_children_api_v1_nodes__node_id__children_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                node_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NodeResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_descendants_api_v1_nodes__node_id__descendants_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                node_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NodeResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_node_edges_api_v1_nodes__node_id__edges_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                node_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NodeEdgeInfo"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_node_graph_api_v1_nodes__node_id__graph_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                node_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GraphResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_node_context_api_v1_nodes__node_id__context_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                node_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NodeContextResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    save_ghost_position_api_v1_nodes__container_id__ghost_positions__node_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                container_id: string;
                node_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GhostPositionUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    save_ghost_edge_handle_api_v1_nodes__container_id__ghost_edge_handles__edge_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                container_id: string;
                edge_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GhostEdgeHandleUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    save_edge_waypoints_api_v1_nodes__container_id__edge_waypoints__edge_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                container_id: string;
                edge_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EdgeWaypointsUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_edges_api_v1_edges__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EdgeResponse"][];
                };
            };
        };
    };
    create_edge_api_v1_edges__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EdgeCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EdgeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_edge_api_v1_edges__edge_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                edge_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EdgeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_edge_api_v1_edges__edge_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                edge_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_edge_api_v1_edges__edge_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                edge_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EdgeUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EdgeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    edge_deletion_snapshot_api_v1_edges__edge_id__deletion_snapshot_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                edge_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeletionSnapshot-Output"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_all_api_v1_export_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExportResponse"];
                };
            };
        };
    };
    export_subtree_api_v1_export__node_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                node_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExportResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_processes_api_v1_processes_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProcessListItem"][];
                };
            };
        };
    };
    create_process_api_v1_processes_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProcessCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProcessDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_process_api_v1_processes__process_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                process_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProcessDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_process_api_v1_processes__process_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                process_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_process_api_v1_processes__process_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                process_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProcessUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProcessDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_participant_api_v1_processes__process_id__participants_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                process_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ParticipantCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ParticipantOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reorder_participants_api_v1_processes__process_id__participants_reorder_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                process_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReorderPayload"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ParticipantOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_participant_api_v1_processes__process_id__participants__participant_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                process_id: string;
                participant_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_message_api_v1_processes__process_id__messages_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                process_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MessageCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_message_api_v1_processes__process_id__messages__message_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                process_id: string;
                message_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_message_api_v1_processes__process_id__messages__message_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                process_id: string;
                message_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MessageUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_fragment_api_v1_processes__process_id__fragments_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                process_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FragmentCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FragmentOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_fragment_api_v1_processes__process_id__fragments__fragment_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                process_id: string;
                fragment_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_fragment_api_v1_processes__process_id__fragments__fragment_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                process_id: string;
                fragment_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FragmentUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FragmentOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_channels_api_v1_processes__process_id__channels_get: {
        parameters: {
            query: {
                a: string;
                b: string;
            };
            header?: never;
            path: {
                process_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChannelOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
}
