/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register */
        post: operations["register_api_v1_auth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/nodes/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Nodes */
        get: operations["list_nodes_api_v1_nodes__get"];
        put?: never;
        /** Create Node */
        post: operations["create_node_api_v1_nodes__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/nodes/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search Nodes */
        get: operations["search_nodes_api_v1_nodes_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/nodes/graph": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Root Graph
         * @description Граф корневого уровня: узлы без родителя + сквозные рёбра.
         */
        get: operations["get_root_graph_api_v1_nodes_graph_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/nodes/alerts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Alerts
         * @description Глобальные алерты незавершённости схемы (только архитектор):
         *     1) атомарные (листовые) узлы без единой связи — «подвисшие»;
         *     2) связи, у которых хотя бы один конец упирается в промежуточный
         *        (контейнерный) узел, а не в атомарный.
         *     Контейнеры в проверке (1) не участвуют: прямых связей у них быть не должно
         *     (это как раз ловит проверка 2), а группировку детей за «подвисание» не считаем.
         */
        get: operations["get_alerts_api_v1_nodes_alerts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/nodes/{node_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Node */
        get: operations["get_node_api_v1_nodes__node_id__get"];
        put?: never;
        post?: never;
        /** Delete Node */
        delete: operations["delete_node_api_v1_nodes__node_id__delete"];
        options?: never;
        head?: never;
        /** Update Node */
        patch: operations["update_node_api_v1_nodes__node_id__patch"];
        trace?: never;
    };
    "/api/v1/nodes/{node_id}/children": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Children */
        get: operations["get_children_api_v1_nodes__node_id__children_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/nodes/{node_id}/descendants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Descendants
         * @description Все потомки узла на любой глубине (без самого узла) — для скоупленного
         *     выбора дальнего конца межуровневой связи: тянешь стрелку на узел-контейнер,
         *     поиск идёт только по его поддереву.
         */
        get: operations["get_descendants_api_v1_nodes__node_id__descendants_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/nodes/{node_id}/edges": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Node Edges
         * @description Внешние связи поддерева узла (он сам + потомки любой глубины) — те, что
         *     исчезнут при удалении узла: ровно один конец внутри поддерева, другой снаружи.
         *     Для предупреждения перед удалением. Чисто внутренние связи ветки не включаем —
         *     они уходят вместе с самой веткой и «потерей связи наружу» не являются.
         *     Направление/имя соседа считаются относительно поддерева (внешний конец).
         */
        get: operations["get_node_edges_api_v1_nodes__node_id__edges_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/nodes/{node_id}/graph": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Node Graph
         * @description Граф для уровня node_id: дочерние узлы + рёбра + гостевые узлы из других уровней.
         */
        get: operations["get_node_graph_api_v1_nodes__node_id__graph_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/nodes/{node_id}/context": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Node Context
         * @description Контекстная схема узла: сам узел + его прямые соседи.
         *     Сосед — другой конец связи, у которой ровно один конец лежит в поддереве
         *     фокуса (сам узел ИЛИ любой его потомок на любой глубине). Конец внутри
         *     поддерева проецируется на фокус, внешний конец — это узел-сосед.
         */
        get: operations["get_node_context_api_v1_nodes__node_id__context_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/nodes/{container_id}/ghost-positions/{node_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Save Ghost Position
         * @description Сохраняет (upsert) координаты гостевого узла node_id на уровне container_id.
         */
        put: operations["save_ghost_position_api_v1_nodes__container_id__ghost_positions__node_id__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/nodes/{container_id}/ghost-edge-handles/{edge_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Save Ghost Edge Handle
         * @description Сохраняет (upsert) хэндл гостевого конца ребра edge_id на уровне container_id,
         *     привязанный к id отображаемой сущности node_id (лист-гость ИЛИ предок-контейнер).
         *
         *     У каждой проекции гостевого конца своя строка — поэтому привязка к свёрнутому
         *     контейнеру и к развёрнутому листу хранятся раздельно и не затирают друг друга.
         */
        put: operations["save_ghost_edge_handle_api_v1_nodes__container_id__ghost_edge_handles__edge_id__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/nodes/{container_id}/edge-waypoints/{edge_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Save Edge Waypoints
         * @description Сохраняет (upsert) кастомный путь ГОСТЕВОЙ стрелки edge_id на уровне container_id.
         *
         *     Пустой список waypoints — сброс в авто-маршрут: строку пер-уровневого слоя удаляем
         *     (нет строки = авто). Путь локальной стрелки сюда не пишется — он в колонке ребра.
         */
        put: operations["save_edge_waypoints_api_v1_nodes__container_id__edge_waypoints__edge_id__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/edges/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Edges */
        get: operations["list_edges_api_v1_edges__get"];
        put?: never;
        /** Create Edge */
        post: operations["create_edge_api_v1_edges__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/edges/{edge_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Edge */
        get: operations["get_edge_api_v1_edges__edge_id__get"];
        put?: never;
        post?: never;
        /** Delete Edge */
        delete: operations["delete_edge_api_v1_edges__edge_id__delete"];
        options?: never;
        head?: never;
        /** Update Edge */
        patch: operations["update_edge_api_v1_edges__edge_id__patch"];
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AlertsResponse */
        AlertsResponse: {
            /**
             * Disconnected Nodes
             * @default []
             */
            disconnected_nodes: components["schemas"]["DisconnectedNodeAlert"][];
            /**
             * Intermediate Edges
             * @default []
             */
            intermediate_edges: components["schemas"]["IntermediateEdgeAlert"][];
        };
        /** AncestorRef */
        AncestorRef: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
        };
        /** Body_login_api_v1_auth_login_post */
        Body_login_api_v1_auth_login_post: {
            /** Grant Type */
            grant_type?: string | null;
            /** Username */
            username: string;
            /** Password */
            password: string;
            /**
             * Scope
             * @default
             */
            scope: string;
            /** Client Id */
            client_id?: string | null;
            /** Client Secret */
            client_secret?: string | null;
        };
        /**
         * DisconnectedNodeAlert
         * @description Атомарный узел без единой связи («подвисший»).
         */
        DisconnectedNodeAlert: {
            /**
             * Node Id
             * Format: uuid
             */
            node_id: string;
            /** Node Name */
            node_name: string;
        };
        /** EdgeCreate */
        EdgeCreate: {
            /** Label */
            label?: string | null;
            /** Technology */
            technology?: string | null;
            /**
             * Source Id
             * Format: uuid
             */
            source_id: string;
            /**
             * Target Id
             * Format: uuid
             */
            target_id: string;
            /** Source Handle */
            source_handle?: string | null;
            /** Target Handle */
            target_handle?: string | null;
        };
        /** EdgeResponse */
        EdgeResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Label */
            label: string | null;
            /** Technology */
            technology: string | null;
            /**
             * Source Id
             * Format: uuid
             */
            source_id: string;
            /**
             * Target Id
             * Format: uuid
             */
            target_id: string;
            /** Source Handle */
            source_handle: string | null;
            /** Target Handle */
            target_handle: string | null;
            /** Waypoints */
            waypoints?: components["schemas"]["Point"][] | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** EdgeUpdate */
        EdgeUpdate: {
            /** Label */
            label?: string | null;
            /** Technology */
            technology?: string | null;
            /** Source Id */
            source_id?: string | null;
            /** Target Id */
            target_id?: string | null;
            /** Source Handle */
            source_handle?: string | null;
            /** Target Handle */
            target_handle?: string | null;
            /** Waypoints */
            waypoints?: components["schemas"]["Point"][] | null;
        };
        /** EdgeWaypointsUpdate */
        EdgeWaypointsUpdate: {
            /** Waypoints */
            waypoints: components["schemas"]["Point"][];
        };
        /** GhostEdgeHandleUpdate */
        GhostEdgeHandleUpdate: {
            /**
             * Node Id
             * Format: uuid
             */
            node_id: string;
            /** Handle */
            handle: string;
        };
        /** GhostNodeResponse */
        GhostNodeResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Role */
            role: string | null;
            /** Technology */
            technology: string | null;
            /** Is External */
            is_external: boolean;
            /**
             * Shape
             * @enum {string}
             */
            shape: "service" | "database" | "broker" | "person";
            /** Node Depth */
            node_depth: number;
            /**
             * Ancestors
             * @default []
             */
            ancestors: components["schemas"]["AncestorRef"][];
            /** Pos X */
            pos_x?: number | null;
            /** Pos Y */
            pos_y?: number | null;
            /**
             * Is Ghost
             * @default true
             * @constant
             * @enum {boolean}
             */
            is_ghost: true;
        };
        /** GhostPositionUpdate */
        GhostPositionUpdate: {
            /** Pos X */
            pos_x: number;
            /** Pos Y */
            pos_y: number;
        };
        /** GraphEdgeResponse */
        GraphEdgeResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Label */
            label: string | null;
            /** Technology */
            technology: string | null;
            /**
             * Source Id
             * Format: uuid
             */
            source_id: string;
            /**
             * Target Id
             * Format: uuid
             */
            target_id: string;
            /**
             * Original Source Id
             * Format: uuid
             */
            original_source_id: string;
            /**
             * Original Target Id
             * Format: uuid
             */
            original_target_id: string;
            /** Original Source Name */
            original_source_name: string;
            /** Original Target Name */
            original_target_name: string;
            /** Source Handle */
            source_handle: string | null;
            /** Target Handle */
            target_handle: string | null;
            /** Waypoints */
            waypoints?: components["schemas"]["Point"][] | null;
        };
        /** GraphResponse */
        GraphResponse: {
            /** Nodes */
            nodes: components["schemas"]["NodeResponse"][];
            /** Edges */
            edges: components["schemas"]["GraphEdgeResponse"][];
            /** Ghost Nodes */
            ghost_nodes: components["schemas"]["GhostNodeResponse"][];
            /**
             * Level Positions
             * @default {}
             */
            level_positions: {
                [key: string]: components["schemas"]["PosXY"];
            };
            /**
             * Level Edge Handles
             * @default {}
             */
            level_edge_handles: {
                [key: string]: string[];
            };
            /**
             * Level Edge Waypoints
             * @default {}
             */
            level_edge_waypoints: {
                [key: string]: components["schemas"]["Point"][];
            };
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * IntermediateEdgeAlert
         * @description Связь, у которой хотя бы один конец упирается в промежуточный
         *     (контейнерный) узел, а не в атомарный.
         */
        IntermediateEdgeAlert: {
            /**
             * Edge Id
             * Format: uuid
             */
            edge_id: string;
            /** Label */
            label: string | null;
            /**
             * Source Id
             * Format: uuid
             */
            source_id: string;
            /** Source Name */
            source_name: string;
            /**
             * Target Id
             * Format: uuid
             */
            target_id: string;
            /** Target Name */
            target_name: string;
            /** Source Is Intermediate */
            source_is_intermediate: boolean;
            /** Target Is Intermediate */
            target_is_intermediate: boolean;
        };
        /**
         * NodeContextResponse
         * @description «Контекстная схема» узла: сам узел + его прямые соседи.
         *     Сосед — другой конец любой связи, у которой ровно один конец лежит в поддереве
         *     фокуса (сам узел или любой его потомок). Рёбра спроецированы: конец внутри
         *     поддерева свёрнут на фокус, внешний конец указывает на узел-соседа.
         *     Соседи отдаются как «гости» (пунктир), focus_ancestors — для рамок предков.
         */
        NodeContextResponse: {
            focus: components["schemas"]["NodeResponse"];
            /**
             * Focus Ancestors
             * @default []
             */
            focus_ancestors: components["schemas"]["AncestorRef"][];
            /**
             * Neighbors
             * @default []
             */
            neighbors: components["schemas"]["GhostNodeResponse"][];
            /**
             * Edges
             * @default []
             */
            edges: components["schemas"]["GraphEdgeResponse"][];
        };
        /** NodeCreate */
        NodeCreate: {
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
            /** Role */
            role?: string | null;
            /** Technology */
            technology?: string | null;
            /** Parent Id */
            parent_id?: string | null;
            /** Flowchart */
            flowchart?: string | null;
            /** Openapi Spec */
            openapi_spec?: string | null;
            /**
             * Is External
             * @default false
             */
            is_external: boolean;
            /**
             * Shape
             * @default service
             * @enum {string}
             */
            shape: "service" | "database" | "broker" | "person";
            /** Pos X */
            pos_x?: number | null;
            /** Pos Y */
            pos_y?: number | null;
        };
        /**
         * NodeEdgeInfo
         * @description Связь узла для предупреждения при удалении: направление + имя связанного узла.
         */
        NodeEdgeInfo: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Label */
            label: string | null;
            /** Technology */
            technology: string | null;
            /**
             * Direction
             * @enum {string}
             */
            direction: "outgoing" | "incoming";
            /**
             * Other Node Id
             * Format: uuid
             */
            other_node_id: string;
            /** Other Node Name */
            other_node_name: string;
        };
        /** NodeResponse */
        NodeResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Description */
            description: string | null;
            /** Role */
            role: string | null;
            /** Technology */
            technology: string | null;
            /** Parent Id */
            parent_id: string | null;
            /** Flowchart */
            flowchart: string | null;
            /** Openapi Spec */
            openapi_spec: string | null;
            /** Pos X */
            pos_x: number | null;
            /** Pos Y */
            pos_y: number | null;
            /** Is External */
            is_external: boolean;
            /**
             * Shape
             * @enum {string}
             */
            shape: "service" | "database" | "broker" | "person";
            /**
             * Has Children
             * @default false
             */
            has_children: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** NodeUpdate */
        NodeUpdate: {
            /** Name */
            name?: string | null;
            /** Description */
            description?: string | null;
            /** Role */
            role?: string | null;
            /** Technology */
            technology?: string | null;
            /** Parent Id */
            parent_id?: string | null;
            /** Flowchart */
            flowchart?: string | null;
            /** Openapi Spec */
            openapi_spec?: string | null;
            /** Pos X */
            pos_x?: number | null;
            /** Pos Y */
            pos_y?: number | null;
            /** Is External */
            is_external?: boolean | null;
            /** Shape */
            shape?: ("service" | "database" | "broker" | "person") | null;
        };
        /**
         * Point
         * @description Точка-сгиб пути стрелки в координатах графа уровня.
         */
        Point: {
            /** X */
            x: number;
            /** Y */
            y: number;
        };
        /** PosXY */
        PosXY: {
            /** Pos X */
            pos_x: number;
            /** Pos Y */
            pos_y: number;
        };
        /** Token */
        Token: {
            /** Access Token */
            access_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
        };
        /** UserCreate */
        UserCreate: {
            /** Username */
            username: string;
            /** Password */
            password: string;
            /**
             * Role
             * @default viewer
             */
            role: string;
        };
        /** UserResponse */
        UserResponse: {
            /** Username */
            username: string;
            /** Role */
            role: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    register_api_v1_auth_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/x-www-form-urlencoded": components["schemas"]["Body_login_api_v1_auth_login_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Token"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_nodes_api_v1_nodes__get: {
        parameters: {
            query?: {
                parent_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NodeResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_node_api_v1_nodes__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NodeCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NodeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_nodes_api_v1_nodes_search_get: {
        parameters: {
            query?: {
                q?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NodeResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_root_graph_api_v1_nodes_graph_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GraphResponse"];
                };
            };
        };
    };
    get_alerts_api_v1_nodes_alerts_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertsResponse"];
                };
            };
        };
    };
    get_node_api_v1_nodes__node_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                node_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NodeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_node_api_v1_nodes__node_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                node_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_node_api_v1_nodes__node_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                node_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NodeUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NodeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_children_api_v1_nodes__node_id__children_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                node_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NodeResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_descendants_api_v1_nodes__node_id__descendants_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                node_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NodeResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_node_edges_api_v1_nodes__node_id__edges_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                node_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NodeEdgeInfo"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_node_graph_api_v1_nodes__node_id__graph_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                node_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GraphResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_node_context_api_v1_nodes__node_id__context_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                node_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NodeContextResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    save_ghost_position_api_v1_nodes__container_id__ghost_positions__node_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                container_id: string;
                node_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GhostPositionUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    save_ghost_edge_handle_api_v1_nodes__container_id__ghost_edge_handles__edge_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                container_id: string;
                edge_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GhostEdgeHandleUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    save_edge_waypoints_api_v1_nodes__container_id__edge_waypoints__edge_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                container_id: string;
                edge_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EdgeWaypointsUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_edges_api_v1_edges__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EdgeResponse"][];
                };
            };
        };
    };
    create_edge_api_v1_edges__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EdgeCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EdgeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_edge_api_v1_edges__edge_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                edge_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EdgeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_edge_api_v1_edges__edge_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                edge_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_edge_api_v1_edges__edge_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                edge_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EdgeUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EdgeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
}
