"""anchor_rel у ghost_positions

Revision ID: 17906408fa51
Revises: 1fae188eae5e
Create Date: 2026-06-15 22:39:20.626913

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '17906408fa51'
down_revision: Union[str, None] = '1fae188eae5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ghost_positions', sa.Column('anchor_rel', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ghost_positions', 'anchor_rel')
    # ### end Alembic commands ###
