"""бизнес-процессы

Revision ID: 1fae188eae5e
Revises: db4fc16c2b50
Create Date: 2026-06-14 22:11:58.880977

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '1fae188eae5e'
down_revision: Union[str, None] = 'db4fc16c2b50'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('business_processes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('scope_node_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['scope_node_id'], ['nodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('process_fragments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('process_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.String(length=8), nullable=False),
    sa.Column('from_order', sa.Integer(), nullable=False),
    sa.Column('to_order', sa.Integer(), nullable=False),
    sa.Column('guard', sa.String(length=256), nullable=True),
    sa.Column('else_guard', sa.String(length=256), nullable=True),
    sa.Column('else_order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['process_id'], ['business_processes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('process_participants',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('process_id', sa.Uuid(), nullable=False),
    sa.Column('node_id', sa.Uuid(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['node_id'], ['nodes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['process_id'], ['business_processes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('process_id', 'node_id', name='uq_participant_node')
    )
    op.create_table('process_messages',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('process_id', sa.Uuid(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('edge_id', sa.Uuid(), nullable=True),
    sa.Column('leg', sa.String(length=8), nullable=False),
    sa.Column('from_participant_id', sa.Uuid(), nullable=False),
    sa.Column('to_participant_id', sa.Uuid(), nullable=False),
    sa.Column('caption', sa.String(length=256), nullable=True),
    sa.ForeignKeyConstraint(['edge_id'], ['edges.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['from_participant_id'], ['process_participants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['process_id'], ['business_processes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_participant_id'], ['process_participants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('edges', sa.Column('is_synchronous', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('edges', 'is_synchronous')
    op.drop_table('process_messages')
    op.drop_table('process_participants')
    op.drop_table('process_fragments')
    op.drop_table('business_processes')
    # ### end Alembic commands ###
