"""каналы брокера: broker_channels + channel_fields

Второй круг документации данных (docs/plan-broker-docs.md §2). Структура брокера —
«контракт» узла, симметрично таблицам у базы; отдельные таблицы, а НЕ обобщение
db_tables: у канала своя мета (доставка, ключ партиционирования, retention), и общая
сущность вышла бы строкой с дюжиной nullable-полей. group_name NOT NULL с пустой
строкой вместо NULL — иначе уникальность «одно имя на группу» не сработала бы вовсе
(в Postgres NULL-ы друг другу не конфликтуют). Обращения к каналам записей не имеют:
их истина — пометки «публикует:/потребляет:» в тексте схем логики вызывающих.

Revision ID: 264a740056a7
Revises: f338f60657d3
Create Date: 2026-08-14 11:58:26.764460

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '264a740056a7'
down_revision: Union[str, None] = 'f338f60657d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('broker_channels',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('node_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('group_name', sa.String(length=128), server_default='', nullable=False),
    sa.Column('kind', sa.String(length=64), server_default='', nullable=False),
    sa.Column('partition_key', sa.String(length=256), server_default='', nullable=False),
    sa.Column('delivery', sa.String(length=64), server_default='', nullable=False),
    sa.Column('retention', sa.String(length=128), server_default='', nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['node_id'], ['nodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('node_id', 'group_name', 'name', name='uq_broker_channel_name')
    )
    op.create_index(op.f('ix_broker_channels_node_id'), 'broker_channels', ['node_id'], unique=False)
    op.create_table('channel_fields',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('channel_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('type', sa.String(length=128), server_default='', nullable=False),
    sa.Column('required', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('order', sa.Integer(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['broker_channels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('channel_id', 'name', name='uq_channel_field_name')
    )
    op.create_index(op.f('ix_channel_fields_channel_id'), 'channel_fields', ['channel_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_channel_fields_channel_id'), table_name='channel_fields')
    op.drop_table('channel_fields')
    op.drop_index(op.f('ix_broker_channels_node_id'), table_name='broker_channels')
    op.drop_table('broker_channels')
    # ### end Alembic commands ###
