"""источник узла: source_ref для идентичности между прогонами агента

Revision ID: 428e9cd20340
Revises: c7d8e9f0a1b2
Create Date: 2026-08-07 19:58:44.795877

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '428e9cd20340'
down_revision: Union[str, None] = 'c7d8e9f0a1b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nodes', sa.Column('source_ref', sa.String(length=512), nullable=True))
    op.create_index('ix_nodes_project_source', 'nodes', ['project_id', 'source_ref'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_nodes_project_source', table_name='nodes')
    op.drop_column('nodes', 'source_ref')
    # ### end Alembic commands ###
