"""администратор и блокировка пользователей

Revision ID: 465bebb8c9d6
Revises: d84f05694ac7
Create Date: 2026-09-30 10:23:46.447477

Схема аддитивная (docs/tasks/admin-users.md, шаг 1): два булевых флага с
серверными дефолтами, существующие строки получают is_admin=false и
is_active=true — все нынешние пользователи остаются активными и без прав
администратора. Первого администратора назначают командой на сервере
(python -m app.admin create-admin).
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '465bebb8c9d6'
down_revision: Union[str, None] = 'd84f05694ac7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_admin', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('users', sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_active')
    op.drop_column('users', 'is_admin')
    # ### end Alembic commands ###
