"""anchor_rel у edge_waypoints

Revision ID: 4acc971e8bc2
Revises: 17906408fa51
Create Date: 2026-06-16 10:32:14.626371

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '4acc971e8bc2'
down_revision: Union[str, None] = '17906408fa51'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('edge_waypoints', sa.Column('anchor_rel', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('edge_waypoints', 'anchor_rel')
    # ### end Alembic commands ###
