"""доступ к проектам по участникам

Revision ID: 4ff27c4efc3f
Revises: 465bebb8c9d6
Create Date: 2026-10-01 23:47:26.828008

Доступ к проектам по участникам (docs/tasks/project-access.md). Схема: таблица
project_members (роль owner/editor/reader, ключ — пара проект+пользователь) и флаг
projects.visible_to_all.

Шаг данных — простым SQL (по миграциям позже собирают Liquibase-changelog для
прода закрытого контура), чтобы после обновления ни у кого ничего не пропало:
  1. все существующие проекты видны всем (visible_to_all = true);
  2. владелец — автор проекта (created_by_id); нет автора — первый по created_at
     администратор; нет и его — первый по created_at architect; пользователей нет
     вовсе — проект остаётся без владельца (допустимо только как наследие миграции);
  3. все пользователи с общей ролью architect — редакторы каждого проекта (кроме
     его владельца).
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '4ff27c4efc3f'
down_revision: Union[str, None] = '465bebb8c9d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_members',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("role IN ('owner', 'editor', 'reader')", name='ck_project_members_role'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('project_id', 'user_id')
    )
    op.create_index(op.f('ix_project_members_user_id'), 'project_members', ['user_id'], unique=False)
    op.add_column('projects', sa.Column('visible_to_all', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###

    # ── Данные: существующие проекты не должны ни у кого пропасть ──
    # 1. Все существующие проекты видны всем.
    op.execute("UPDATE projects SET visible_to_all = TRUE")
    # 2. Владелец: автор, иначе первый администратор, иначе первый architect.
    op.execute(
        """
        INSERT INTO project_members (project_id, user_id, role, created_at)
        SELECT t.project_id, t.owner_id, 'owner', CURRENT_TIMESTAMP
        FROM (
            SELECT p.id AS project_id,
                   COALESCE(
                       p.created_by_id,
                       (SELECT u.id FROM users u WHERE u.is_admin
                        ORDER BY u.created_at LIMIT 1),
                       (SELECT u.id FROM users u WHERE u.role = 'architect'
                        ORDER BY u.created_at LIMIT 1)
                   ) AS owner_id
            FROM projects p
        ) t
        WHERE t.owner_id IS NOT NULL
        """
    )
    # 3. Все architect — редакторы каждого проекта, где они ещё не участники.
    op.execute(
        """
        INSERT INTO project_members (project_id, user_id, role, created_at)
        SELECT p.id, u.id, 'editor', CURRENT_TIMESTAMP
        FROM projects p CROSS JOIN users u
        WHERE u.role = 'architect'
          AND NOT EXISTS (
              SELECT 1 FROM project_members m
              WHERE m.project_id = p.id AND m.user_id = u.id
          )
        """
    )


def downgrade() -> None:
    # Участия и видимость теряются целиком: до этой ревизии доступ был у всех ко всему.
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'visible_to_all')
    op.drop_index(op.f('ix_project_members_user_id'), table_name='project_members')
    op.drop_table('project_members')
    # ### end Alembic commands ###
