"""канал на связи: edges.channel

Решение пользователя №4 (docs/plan-broker-docs.md §4): стрелка «сервис → брокер»
обязана называть топик/очередь. Поле — строка-ССЫЛКА, а не FK на broker_channels:
тот же принцип, что у пометок «публикует:/потребляет:» — связь по имени, резолв на
чтении по структуре брокера-конца, а шов проверяет алерт AL31. FK привязал бы
стрелку к строке структуры и требовал бы инвалидации при каждом переименовании
канала. nullable — у связей без брокера канала не бывает, и легаси-строки валидны.

Revision ID: 6f0e2f9b617c
Revises: 264a740056a7
Create Date: 2026-08-14 13:09:05.272474

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '6f0e2f9b617c'
down_revision: Union[str, None] = '264a740056a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('edges', sa.Column('channel', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('edges', 'channel')
    # ### end Alembic commands ###
