"""параметры конфигурации config_params

Третья семья фактов после структуры БД и каналов брокера (docs/plan-config-docs.md):
переменные окружения и настройки, от которых зависят развилки схем логики. Владелец —
САМ СЕРВИС, а не отдельный узел-хранилище, поэтому таблица одна и плоская: ни второго
уровня (как колонки у таблиц и поля у каналов), ни группы — а значит, и пустых строк
вместо NULL ради уникальности здесь не понадобилось. ЗНАЧЕНИЙ НЕТ: default_value —
текст дефолта из кода, не значение среды.

Revision ID: 7930ba83ee51
Revises: 5c7ab8de46d6
Create Date: 2026-08-17 15:38:21.026577

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '7930ba83ee51'
down_revision: Union[str, None] = '5c7ab8de46d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('config_params',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('node_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('value_type', sa.String(length=64), server_default='', nullable=False),
    sa.Column('required', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('default_value', sa.String(length=512), server_default='', nullable=False),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['node_id'], ['nodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('node_id', 'name', name='uq_config_param_name')
    )
    op.create_index(op.f('ix_config_params_node_id'), 'config_params', ['node_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_config_params_node_id'), table_name='config_params')
    op.drop_table('config_params')
    # ### end Alembic commands ###
