"""структура БД: таблицы, колонки, обращения к данным

Первый круг документации данных (docs/plan-db-docs.md). Структура — «контракт»
узла-базы, симметрично openapi_spec у сервиса; обращения (doc_data_access) — её
ИСПОЛЬЗОВАНИЕ, живущее у вызывающего, в доке его операции. Хранится записями, а не
текстом mermaid: ER-диаграмма производна, а из текста диаграммы не построить
обратный индекс «кто трогает orders.status», ради которого всё и затевалось.

Revision ID: 8e444fffd977
Revises: b3d81f60a4c7
Create Date: 2026-08-12 11:05:37.803386

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '8e444fffd977'
down_revision: Union[str, None] = 'b3d81f60a4c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('db_tables',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('node_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('schema_name', sa.String(length=128), server_default='', nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['node_id'], ['nodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('node_id', 'schema_name', 'name', name='uq_db_table_name')
    )
    op.create_index(op.f('ix_db_tables_node_id'), 'db_tables', ['node_id'], unique=False)
    op.create_table('db_columns',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('table_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('type', sa.String(length=128), server_default='', nullable=False),
    sa.Column('nullable', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('is_primary_key', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('references_column_id', sa.Uuid(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('order', sa.Integer(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['references_column_id'], ['db_columns.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['table_id'], ['db_tables.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('table_id', 'name', name='uq_db_column_name')
    )
    op.create_index(op.f('ix_db_columns_table_id'), 'db_columns', ['table_id'], unique=False)
    op.create_table('doc_data_access',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('node_doc_id', sa.Uuid(), nullable=False),
    sa.Column('table_id', sa.Uuid(), nullable=False),
    sa.Column('column_id', sa.Uuid(), nullable=True),
    sa.Column('mode', sa.String(length=8), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['column_id'], ['db_columns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['node_doc_id'], ['node_docs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['table_id'], ['db_tables.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_doc_data_access_node_doc_id'), 'doc_data_access', ['node_doc_id'], unique=False)
    op.create_index(op.f('ix_doc_data_access_table_id'), 'doc_data_access', ['table_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_doc_data_access_table_id'), table_name='doc_data_access')
    op.drop_index(op.f('ix_doc_data_access_node_doc_id'), table_name='doc_data_access')
    op.drop_table('doc_data_access')
    op.drop_index(op.f('ix_db_columns_table_id'), table_name='db_columns')
    op.drop_table('db_columns')
    op.drop_index(op.f('ix_db_tables_node_id'), table_name='db_tables')
    op.drop_table('db_tables')
    # ### end Alembic commands ###
