"""позиция плашки связи (label_t)

Revision ID: db4fc16c2b50
Revises: c1d2e3f4a5b6
Create Date: 2026-06-11 23:40:24.012960

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'db4fc16c2b50'
down_revision: Union[str, None] = 'c1d2e3f4a5b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('edges', sa.Column('label_t', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('edges', 'label_t')
    # ### end Alembic commands ###
