"""node status (as-is/to-be/deprecated)

Revision ID: df8eca556e4b
Revises: df8f375618d9
Create Date: 2026-06-19 13:08:10.912299

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'df8eca556e4b'
down_revision: Union[str, None] = 'df8f375618d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nodes', sa.Column('status', sa.String(length=16), server_default='existing', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('nodes', 'status')
    # ### end Alembic commands ###
