"""версия шага и курсор процессов

Revision ID: fed34b60cbc8
Revises: 8d3f21a7c94e
Create Date: 2026-08-18 19:48:48.863195

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'fed34b60cbc8'
down_revision: Union[str, None] = '8d3f21a7c94e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('process_messages', sa.Column('version', sa.Integer(), server_default='1', nullable=False))
    op.add_column('projects', sa.Column('process_rev', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'process_rev')
    op.drop_column('process_messages', 'version')
    # ### end Alembic commands ###
